const tokenType = {
    USER_REGISTRATION: "USER_REGISTRATION_SECRET_KEY",
    RESET_PASSWORD: "RESET_PASSWORD_SECRET_KEY",
    INVITE_USER: "INVITE_NEW_USER_SECRET_KEY"
}

module.exports = {tokenType};